import "@/lib/polyfills";
import {
  Connection,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
  Keypair,
} from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  ExtensionType,
  getMintLen,
  createInitializeMintInstruction,
  createInitializeMetadataPointerInstruction,
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  createMintToInstruction,
  createSetAuthorityInstruction,
  AuthorityType,
  getTokenMetadata,
  getMint,
} from "@solana/spl-token";
import {
  createInitializeInstruction as createInitializeTokenMetadataInstruction,
  createUpdateAuthorityInstruction as createUpdateMetadataAuthorityInstruction,
  pack as packTokenMetadata,
  type TokenMetadata,
} from "@solana/spl-token-metadata";
import type { SolanaProvider } from "@/components/wallet/WalletContext";
import { rpcForCluster, isMainnetRpcAccessError, type Cluster } from "./cluster";
import { assertSolanaAddress } from "./address";

export async function getWalletBalanceSol(
  address: string,
  cluster: Cluster,
): Promise<number> {
  const rpcUrl = rpcForCluster(cluster);
  const connection = new Connection(rpcUrl, "confirmed");
  const pk = new PublicKey(assertSolanaAddress(address, "Wallet address"));
  const lamports = await connection.getBalance(pk, "confirmed");
  return lamports / LAMPORTS_PER_SOL;
}

export type SendPaymentArgs = {
  provider: SolanaProvider;
  fromAddress: string;
  toAddress: string;
  amountSol: number;
  cluster: Cluster;
};

export async function sendPayment({
  provider,
  fromAddress,
  toAddress,
  amountSol,
  cluster,
}: SendPaymentArgs): Promise<string> {
  const rpcUrl = rpcForCluster(cluster);
  console.info("[mint] sendPayment cluster=", cluster, "rpc=", rpcUrl);
  const connection = new Connection(rpcUrl, "confirmed");
  const fromPk = new PublicKey(assertSolanaAddress(fromAddress, "Sender wallet address"));
  const toPk = new PublicKey(assertSolanaAddress(toAddress, "Recipient wallet address"));
  const lamports = Math.round(amountSol * LAMPORTS_PER_SOL);

  let blockhash: string;
  let lastValidBlockHeight: number;
  try {
    const bh = await connection.getLatestBlockhash("confirmed");
    blockhash = bh.blockhash;
    lastValidBlockHeight = bh.lastValidBlockHeight;
  } catch (err) {
    console.error("[mint] getLatestBlockhash failed", { cluster, rpcUrl, err });
    if (cluster === "mainnet" && isMainnetRpcAccessError(err)) {
      throw new Error(
        "Mainnet RPC is unavailable from the browser (403 from public endpoint). " +
          "Set VITE_SOLANA_MAINNET_RPC_URL to a browser-accessible RPC (Helius, QuickNode, Triton, Alchemy) and reload.",
      );
    }
    throw new Error(
      `Failed to reach Solana ${cluster} RPC: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  const tx = new Transaction({
    feePayer: fromPk,
    blockhash,
    lastValidBlockHeight,
  }).add(
    SystemProgram.transfer({
      fromPubkey: fromPk,
      toPubkey: toPk,
      lamports,
    }),
  );

  let signature: string;
  if (provider.signAndSendTransaction) {
    const res = await provider.signAndSendTransaction(tx);
    signature = res.signature;
  } else {
    const signed = await provider.signTransaction(tx);
    signature = await connection.sendRawTransaction(signed.serialize(), {
      skipPreflight: false,
    });
  }

  await connection.confirmTransaction(
    { signature, blockhash, lastValidBlockHeight },
    "confirmed",
  );
  return signature;
}

/**
 * Generate a Token-2022 mint keypair upfront (callers need the mint address
 * before signing so they can pre-upload off-chain JSON metadata pointing at it).
 */
export function generateMintKeypair(): Keypair {
  return Keypair.generate();
}

export type MintTokenArgs = {
  provider: SolanaProvider;
  payerAddress: string;
  cluster: Cluster;
  decimals: number;
  initialSupply: string;
  revokeFreeze: boolean;
  revokeMint: boolean;
  /** When true, metadata update authority is permanently revoked after init. */
  revokeUpdate: boolean;
  /** Mint keypair generated by the caller (so the metadata URI can reference it). */
  mintKeypair: Keypair;
  /** On-chain metadata fields (Token-2022 Token Metadata extension). */
  metadata: {
    name: string;
    symbol: string;
    /** HTTPS URI to the off-chain JSON manifest (image, description, socials). */
    uri: string;
  };
};

export type MintTokenResult = {
  mintAddress: string;
  ataAddress: string;
  signature: string;
  /**
   * Resolved metadata update authority after mint confirmation. Read directly
   * from the on-chain TokenMetadata extension via `getTokenMetadata`.
   *  - `null`  → authority was permanently revoked (revokeUpdate=true)
   *  - string  → base58 address that controls future metadata updates
   */
  metadataUpdateAuthority: string | null;
};

/**
 * Creates a Token-2022 mint with on-chain metadata via the
 * MetadataPointer + TokenMetadata extensions, mints initial supply, and
 * optionally revokes mint/freeze/update authorities — all in one transaction.
 *
 * The metadata Update Authority is REAL: it lives in the on-chain
 * TokenMetadata extension. Setting `revokeUpdate` permanently nulls it via
 * `createUpdateAuthorityInstruction`, mirroring how mint/freeze authorities
 * are revoked. There is no fake "update" toggle anywhere.
 *
 * Off-chain JSON (image, description, socials, external_url) is hosted by the
 * server (see `src/server/metadata.functions.ts`) and referenced through the
 * `uri` field stored on-chain — the standard Solana / Metaplex pattern.
 */
export async function mintToken({
  provider,
  payerAddress,
  cluster,
  decimals,
  initialSupply,
  revokeFreeze,
  revokeMint,
  revokeUpdate,
  mintKeypair,
  metadata,
}: MintTokenArgs): Promise<MintTokenResult> {
  const rpcUrl = rpcForCluster(cluster);
  console.info("[mint] mintToken cluster=", cluster, "rpc=", rpcUrl);
  const connection = new Connection(rpcUrl, "confirmed");
  const payer = new PublicKey(assertSolanaAddress(payerAddress, "Payer wallet address"));

  const mintPk = mintKeypair.publicKey;
  // ATA must be derived against the Token-2022 program.
  const ata = getAssociatedTokenAddressSync(
    mintPk,
    payer,
    false,
    TOKEN_2022_PROGRAM_ID,
  );

  // ---------------------------------------------------------------------------
  // Authority decisions (single source of truth for ALL three authorities).
  //
  // Each authority is initialized to the connected wallet, then optionally
  // revoked (set to null) in the SAME atomic transaction. Either both
  // assignment and revocation succeed, or the whole mint fails — there is
  // no window where the on-chain state diverges from the user's selection.
  //
  //   revokeMint   = true  → MintTokens authority   → null  after init
  //                  false → MintTokens authority   → wallet (user can mint more)
  //   revokeFreeze = true  → FreezeAccount authority → null
  //                  false → FreezeAccount authority → wallet (user can freeze)
  //   revokeUpdate = true  → Metadata updateAuthority → null
  //                  false → Metadata updateAuthority → wallet (user can edit)
  //
  // The revoke instructions are appended below in this exact order:
  //   freeze → update → mint
  // (Mint last because we need MintTokens authority to mint the initial supply.)
  // ---------------------------------------------------------------------------
  const initialMintAuthority: PublicKey = payer;
  const initialFreezeAuthority: PublicKey = payer;
  const initialUpdateAuthority: PublicKey = payer;

  const finalMintAuthority: PublicKey | null = revokeMint ? null : payer;
  const finalFreezeAuthority: PublicKey | null = revokeFreeze ? null : payer;
  const finalUpdateAuthority: PublicKey | null = revokeUpdate ? null : payer;

  console.info("[mint] authority plan", {
    mint: mintPk.toBase58(),
    mintAuthority: {
      initial: initialMintAuthority.toBase58(),
      final: finalMintAuthority ? finalMintAuthority.toBase58() : null,
      revoke: revokeMint,
    },
    freezeAuthority: {
      initial: initialFreezeAuthority.toBase58(),
      final: finalFreezeAuthority ? finalFreezeAuthority.toBase58() : null,
      revoke: revokeFreeze,
    },
    updateAuthority: {
      initial: initialUpdateAuthority.toBase58(),
      final: finalUpdateAuthority ? finalUpdateAuthority.toBase58() : null,
      revoke: revokeUpdate,
    },
  });

  // Build the on-chain TokenMetadata struct so we can size the mint account
  // correctly. additionalMetadata is intentionally empty — socials live in
  // the off-chain JSON to keep the on-chain footprint (and tx size) small.
  // NOTE: size is computed from the INITIAL authority. Revocation later in
  // the same tx swaps the authority pubkey for the all-zero pubkey, which
  // is the same on-disk size, so this stays accurate.
  const tokenMetadata: TokenMetadata = {
    mint: mintPk,
    name: metadata.name,
    symbol: metadata.symbol,
    uri: metadata.uri,
    additionalMetadata: [],
    updateAuthority: initialUpdateAuthority,
  };

  // Mint account size = base mint (with extensions) + tokenMetadata extension
  // bytes (which lives at the end of the account, not in getMintLen).
  const baseMintLen = getMintLen([ExtensionType.MetadataPointer]);
  // Token Metadata extension prefix: 4-byte type + length headers (TYPE_SIZE + LENGTH_SIZE).
  const METADATA_EXTENSION_PREFIX = 4;
  const metadataLen = METADATA_EXTENSION_PREFIX + packTokenMetadata(tokenMetadata).length;
  const accountSize = baseMintLen + metadataLen;
  const lamportsForMint = await connection.getMinimumBalanceForRentExemption(accountSize);

  const supplyBI = BigInt(initialSupply);
  const factor = BigInt(10) ** BigInt(decimals);
  const baseUnits = supplyBI * factor;

  let failurePoint = "prepare";

  async function getFreshBlockhash(): Promise<{ blockhash: string; lastValidBlockHeight: number }> {
    failurePoint = "getLatestBlockhash";
    try {
      return await connection.getLatestBlockhash("confirmed");
    } catch (err) {
      console.error("[mint] getLatestBlockhash failed", { cluster, rpcUrl, err });
      if (cluster === "mainnet" && isMainnetRpcAccessError(err)) {
        throw new Error(
          "Mainnet RPC is unavailable from the browser (403 from public endpoint). " +
            "Set VITE_SOLANA_MAINNET_RPC_URL to a browser-accessible RPC and reload.",
        );
      }
      throw new Error(
        `Failed to reach Solana ${cluster} RPC: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  try {
    const { blockhash, lastValidBlockHeight } = await getFreshBlockhash();

    failurePoint = "buildTransaction";
    const tx = new Transaction({
      feePayer: payer,
      blockhash,
      lastValidBlockHeight,
    });

    tx.add(
      // 1. Allocate the mint account sized for MetadataPointer + TokenMetadata.
      SystemProgram.createAccount({
        fromPubkey: payer,
        newAccountPubkey: mintPk,
        lamports: lamportsForMint,
        space: baseMintLen, // metadata extension is appended after init
        programId: TOKEN_2022_PROGRAM_ID,
      }),
      // 2. Set the metadata pointer to point at the mint itself (self-hosted metadata).
      createInitializeMetadataPointerInstruction(
        mintPk,
        payer,
        mintPk,
        TOKEN_2022_PROGRAM_ID,
      ),
      // 3. Initialize the mint (must come AFTER all extension initializers).
      //    The mint authority and freeze authority assigned here are the REAL
      //    on-chain authorities. They may be revoked later in this same tx.
      createInitializeMintInstruction(
        mintPk,
        decimals,
        initialMintAuthority, // mint authority (handles MINT REVOKE below)
        initialFreezeAuthority, // freeze authority (handles FREEZE REVOKE below)
        TOKEN_2022_PROGRAM_ID,
      ),
      // 4. Initialize the on-chain Token Metadata (name/symbol/uri + update authority).
      //    The update authority assigned here IS the real on-chain authority.
      //    Wallets and explorers will treat `initialUpdateAuthority` as the
      //    sole signer that can update name/symbol/uri/additionalMetadata.
      createInitializeTokenMetadataInstruction({
        programId: TOKEN_2022_PROGRAM_ID,
        metadata: mintPk,
        updateAuthority: initialUpdateAuthority,
        mint: mintPk,
        mintAuthority: payer,
        name: metadata.name,
        symbol: metadata.symbol,
        uri: metadata.uri,
      }),
      // 5. Pay rent for the metadata extension bytes that were just appended.
      //    SystemProgram.transfer "tops up" the mint account so it stays rent-exempt
      //    after the metadata extension grew the account.
    );

    // The metadata account grew the on-chain account; ensure it stays rent-exempt.
    const totalLamportsRequired = await connection.getMinimumBalanceForRentExemption(
      accountSize,
    );
    if (totalLamportsRequired > lamportsForMint) {
      tx.add(
        SystemProgram.transfer({
          fromPubkey: payer,
          toPubkey: mintPk,
          lamports: totalLamportsRequired - lamportsForMint,
        }),
      );
    }

    // 6. Create the ATA and mint the initial supply to it.
    tx.add(
      createAssociatedTokenAccountInstruction(
        payer,
        ata,
        payer,
        mintPk,
        TOKEN_2022_PROGRAM_ID,
      ),
      createMintToInstruction(
        mintPk,
        ata,
        payer,
        baseUnits,
        [],
        TOKEN_2022_PROGRAM_ID,
      ),
    );

    // -------------------------------------------------------------------------
    // 7. Authority finalization. Order matters:
    //    a) FREEZE — safe to revoke any time after init.
    //    b) UPDATE — safe to revoke any time after metadata init.
    //    c) MINT   — MUST come last because we needed it above to mint the
    //                initial supply. Revoking earlier would break createMintTo.
    // -------------------------------------------------------------------------

    // (a) FREEZE AUTHORITY
    if (revokeFreeze) {
      console.info("[mint] appending freeze-authority revoke instruction", {
        mint: mintPk.toBase58(),
        oldAuthority: initialFreezeAuthority.toBase58(),
        newAuthority: null,
      });
      tx.add(
        createSetAuthorityInstruction(
          mintPk,
          initialFreezeAuthority,
          AuthorityType.FreezeAccount,
          null,
          [],
          TOKEN_2022_PROGRAM_ID,
        ),
      );
    } else {
      console.info("[mint] keeping freeze authority on connected wallet", {
        mint: mintPk.toBase58(),
        freezeAuthority: initialFreezeAuthority.toBase58(),
      });
    }

    // (b) METADATA UPDATE AUTHORITY
    if (revokeUpdate) {
      console.info("[mint] appending update-authority revoke instruction", {
        mint: mintPk.toBase58(),
        oldAuthority: initialUpdateAuthority.toBase58(),
        newAuthority: null,
      });
      tx.add(
        createUpdateMetadataAuthorityInstruction({
          programId: TOKEN_2022_PROGRAM_ID,
          metadata: mintPk,
          oldAuthority: initialUpdateAuthority,
          newAuthority: null,
        }),
      );
    } else {
      console.info("[mint] keeping update authority on connected wallet", {
        mint: mintPk.toBase58(),
        updateAuthority: initialUpdateAuthority.toBase58(),
      });
    }

    // (c) MINT AUTHORITY — must be LAST so the initial supply mint above succeeds.
    if (revokeMint) {
      console.info("[mint] appending mint-authority revoke instruction", {
        mint: mintPk.toBase58(),
        oldAuthority: initialMintAuthority.toBase58(),
        newAuthority: null,
      });
      tx.add(
        createSetAuthorityInstruction(
          mintPk,
          initialMintAuthority,
          AuthorityType.MintTokens,
          null,
          [],
          TOKEN_2022_PROGRAM_ID,
        ),
      );
    } else {
      console.info("[mint] keeping mint authority on connected wallet", {
        mint: mintPk.toBase58(),
        mintAuthority: initialMintAuthority.toBase58(),
      });
    }

    tx.partialSign(mintKeypair);

    let signature: string;
    if (provider.signTransaction) {
      failurePoint = "signTransaction";
      const signed = await provider.signTransaction(tx);

      failurePoint = "sendRawTransaction";
      signature = await connection.sendRawTransaction(signed.serialize(), {
        skipPreflight: false,
        maxRetries: 5,
      });
    } else if (provider.signAndSendTransaction) {
      failurePoint = "signAndSendTransaction";
      const res = await provider.signAndSendTransaction(tx);
      signature = res.signature;
    } else {
      throw new Error("Connected wallet does not support Solana transaction signing.");
    }

    failurePoint = "confirmTransaction";
    await connection.confirmTransaction(
      { signature, blockhash, lastValidBlockHeight },
      "confirmed",
    );

    // -------------------------------------------------------------------------
    // Post-confirmation verification: read the on-chain TokenMetadata extension
    // back from the mint and assert the authority matches what we intended.
    // This is what makes the "revoke update" claim real — we don't trust the
    // instruction list, we read state from the chain.
    // -------------------------------------------------------------------------
    failurePoint = "verifyMetadataAuthority";
    let onChainAuthority: string | null = null;
    try {
      const onChain = await getTokenMetadata(connection, mintPk, "confirmed", TOKEN_2022_PROGRAM_ID);
      if (!onChain) {
        throw new Error("TokenMetadata extension missing from mint after confirmation");
      }
      onChainAuthority = onChain.updateAuthority ? onChain.updateAuthority.toBase58() : null;
      const expected = finalUpdateAuthority ? finalUpdateAuthority.toBase58() : null;
      console.info("[mint] metadata update-authority verified", {
        mint: mintPk.toBase58(),
        expected,
        onChain: onChainAuthority,
        revokeUpdate,
      });
      if (onChainAuthority !== expected) {
        throw new Error(
          `Metadata update authority mismatch after mint. Expected ${expected ?? "null (revoked)"}, on-chain ${onChainAuthority ?? "null"}.`,
        );
      }
    } catch (verifyErr) {
      console.error("[mint] metadata authority verification failed", {
        mint: mintPk.toBase58(),
        revokeUpdate,
        err: verifyErr,
      });
      throw verifyErr;
    }

    return {
      mintAddress: mintPk.toBase58(),
      ataAddress: ata.toBase58(),
      signature,
      metadataUpdateAuthority: onChainAuthority,
    };
  } catch (err) {
    console.error("[mint] mintToken failed", { cluster, failurePoint, err });
    const msg = err instanceof Error ? err.message : String(err);
    if (/block height exceeded|blockhash not found|TransactionExpired|expired/i.test(msg)) {
      throw new Error(
        "Mint transaction expired before it was confirmed. Please click Try Again to build a fresh mint transaction.",
      );
    }
    throw err;
  }
}
